# Основной writer — вывод в консоль
writer = console
writer.format = {date: HH:mm:ss} [{level}] {class}.{method}() {message}

# Дополнительный writer — запись в файл
writer2 = file
writer2.file = server.log
writer2.format = {date: yyyy-MM-dd HH:mm:ss.SSS} [{level}] {thread} {class}.{method}() {message}

# Уровни логирования
level = INFOе

# Уровень для конкретных пакетов (опционально)
level.ru.kessi.server = DEBUG
level.ru.kessi.common = INFO
